### ISSUE TITLE
US 1 - List of Galleries

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#1]
# Value Proposition / User Story

*As a user* I want to have a list of galleries in Hamburg
in order to get an overview of all galleries

# Description (text, scribble, wireframe, design)

![US1 Art Gallery App](https://user-images.githubusercontent.com/77647508/120714293-4a59d480-c4c3-11eb-8409-33685053e95e.png)

# Acceptance Criteria

- [x] Cards are sorted alphabetically ascending by name of gallery
- [x] Cards contain an image of the inside or outside of gallery, name, art style, opening hours and entrance fee
- [x] Screen is scrollable

# Complexity (low, mid, high)
mid

# Tasks

- [x] Create feature branch
- [x] Build H1
- [x] Build card component (storybook)
- [x] Add cards to App
- [x] Add basic global styles

**Comment by clemensschueller** [comment]
# Value Proposition / User Story

*As a user* I want to have a list of galleries
in order to get an overview of all galleries

# Description (text, scribble, wireframe, design)

# Acceptance Criteria

**Comment by clemensschueller** [comment]
Everything successfully implemented
