### ISSUE TITLE
US 5 - Add local storage

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#10]
# Value Proposition
As a user I want to have my bookmarks saved on the app

# Description
By reloading the app, data (bookmarks) do not get lost.

#Acceptance Criteria
- [x] When bookmarking preferred galleries, the bookmark should be shown on the bookmark page, even reloading app

#Tasks
- [x] Create feature branch
- [x] Add component with hook
- [x] Add file with logic
