### ISSUE TITLE
US 7 - Add map

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#11]
# Value Proposition / User Story
As a user I want to see galleries on a map in order to see whether the gallery is far or near.
# Description
![US7 Map Function(1)](https://user-images.githubusercontent.com/77647508/124754313-586b9c80-df2a-11eb-9d6b-fbf1c545deb1.png)

# Acceptance Criteria
- [ ] Nav bar has a button for map to access map
- [ ] Galleries are pinned on map
- [ ] Click on pin shows small info box
# Complexity level
high
# Tasks
- [ ] Installation of mapbox
- [ ] Feature branch
- [ ] Build map component
- [ ] Add functions
- [ ] Extend data.json with location data
- [ ] Add additional map button on nav bar
