### ISSUE TITLE
US 6 - Start Page

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#14]
# Value Proposition / User Story
As a user I want a start into the app
# Description
![US6 Start Page](https://user-images.githubusercontent.com/77647508/124756523-d4ff7a80-df2c-11eb-9d53-c06c1a9a5cbe.png)

# Acceptance Criteria
- [x] Start page has a home/start button on the nav bar on the very left
- [x] a big painting of Hamburg as background image
- [x] A welcome text is shown
- [x] App logo on top of screen
# Complexity
low
# Tasks
- [x] Feature branch
- [x] Add Start / Home button to navigation bar
- [x] Add functionality
