### ISSUE TITLE
US 2 - Detailed Gallery Info

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#2]
# Value Proposition / User Story

As a user I want to click on a gallery in order to see additional information

# Description
![US2 Art Gallery Details](https://user-images.githubusercontent.com/77647508/120720721-dc1a0f80-c4cc-11eb-8e92-a4d943068898.png)

# Acceptance Criteria

- [x] Below Photo infos are shown: name of gallery, opening hours, entrance fee, and (scrollable) description about gallery
- [x] At the bottom there is a closing button to close card in order to get back to card list

# Complexity
mid

# Tasks

- [x] Create feature branch
- [x] Build info card component
- [x] Add function to get back to list
- [x] Add styles

**Comment by badabam** [comment]
You should move the image slider ("swiping") into a seperate story.
