### ISSUE TITLE
US 3 - Toggle Bookmark

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#3]
# Value Proposition

As a user I want to bookmark certain galleries so that I can find them faster

# Description
![US3 Toogle Bookmarks](https://user-images.githubusercontent.com/77647508/120758937-bb74a880-c512-11eb-9d01-ddc5f1e1cf36.png)

# Acceptance Criteria

- [x] Heart-shaped Bookmark can toggle two different colors - grey and red
- [x] It toggles by clicking
- [x] The bookmark option only appears in the detailed card view
- [x] Bookmarks are active when toggled red

# Complexity
low

# Tasks

- [x] Create and Design bookmark
- [x] Add active and inactive functionality

**Comment by clemensschueller** [comment]
I replaced the heart shaped bookmark button with a plus for unbookmarked and an anchor for bookmarked
