### ISSUE TITLE
US 4 - Filter Function

### ISSUE THREAD

**Issue by clemensschueller** [clemensschueller/capstone-project#4]
# Value Proposition

As a user I want to filter galleries in order to only see preferred galleries

# Description
![US3 Filter Function](https://user-images.githubusercontent.com/77647508/120760715-b9134e00-c514-11eb-9fda-0ee61c0c6676.png)

# Acceptance Criteria

- [x] There are three possibilities to filter galleries: all, art styles, bookmarked
- [x] Each filter method is accessible by clicking on it
- [x] The styles filter shows art styles in tile view with clickable buttons
- [x] The bookmark filter shows only active bookmarks
- [x] The filter is always present
# Complexity
high
# Tasks

- [x] Create feature branch
- [x] Create art styles page
- [x] Add logic

**Comment by badabam** [comment]
I'd say this is "high complexity". Besides that: nice user story!

**Comment by clemensschueller** [comment]
I created a navigation bar with 'All' and 'Bookmarked'. I'm going to replace the third tab with a map in a next user story
